(function () {
  const data = window.SPARQL_CORRECTION_DATA || null;
  const EXPORT_SCHEMA = "musparql.sparql-correction-review-export.v1";
  const EDIT_TYPES = [
    "syntax_correction", "endpoint_dialect_adaptation", "parameter_instantiation",
    "benchmark_specialization", "federation_rewrite", "performance_optimization", "other",
  ];
  const els = Object.fromEntries([
    "datasetId", "recordCount", "visibleCount", "reviewedCount", "searchInput", "kgFilter",
    "categoryFilter", "decisionFilter", "recordList", "emptyState", "detailView", "detailMeta",
    "detailTitle", "priorityBadge", "categoryBadge", "holdoutWarning", "baseSparql", "triageSummary",
    "executionDetails", "prevBtn", "nextBtn", "editTypeInput", "proposalOriginInput", "proposalModelInput",
    "proposedSparqlInput", "rationaleInput", "evidenceIdsInput", "reviewerNoteInput", "validationMessage",
    "evidenceCount", "evidenceList", "exportCorrectionsBtn", "clearCorrectionStateBtn",
  ].map((id) => [id, document.getElementById(id)]));
  const decisionButtons = Array.from(document.querySelectorAll("[data-decision]"));

  window.MUSPARQL_CORRECTION_SCHEMA = { normalizeReview, validateReview, exportPayload };
  if (!data || !Array.isArray(data.records) || !data.records.length) return;

  const storageKey = `musparql-sparql-correction:v1:${data.dataset_id}`;
  let reviews = loadReviews();
  const state = { selected: data.records[0].candidate_id, search: "", kg: "all", category: "all", decision: "all" };
  els.emptyState.classList.add("hidden"); els.detailView.classList.remove("hidden");
  els.datasetId.textContent = data.dataset_id; els.recordCount.textContent = String(data.record_count);
  fillSelect(els.kgFilter, ["all", ...unique(data.records.map((r) => r.kg_id))], "All KGs");
  fillSelect(els.categoryFilter, ["all", ...unique(data.records.map((r) => r.triage?.category))], "All triage classes");
  fillSelect(els.decisionFilter, ["all", "unreviewed", "approve_edit", "no_edit", "defer"], "All decisions");
  fillSelect(els.editTypeInput, ["", ...EDIT_TYPES], "Select an edit type");
  bind(); render();

  function unique(values) { return [...new Set(values.filter(Boolean))].sort(); }
  function fillSelect(select, values, first) { select.innerHTML = ""; values.forEach((value, i) => { const option = document.createElement("option"); option.value = value; option.textContent = i === 0 ? first : value.replaceAll("_", " "); select.appendChild(option); }); }
  function loadReviews() { try { return JSON.parse(localStorage.getItem(storageKey) || "{}"); } catch (_) { return {}; } }
  function saveReviews() { localStorage.setItem(storageKey, JSON.stringify(reviews)); }
  function normalizeReview(value) { return { decision: value?.decision || "", proposed_sparql: value?.proposed_sparql || "", edit_type: value?.edit_type || "", rationale: value?.rationale || "", evidence_ids: Array.isArray(value?.evidence_ids) ? value.evidence_ids : [], proposal_origin: value?.proposal_origin || "human", proposal_model: value?.proposal_model || "", reviewer_note: value?.reviewer_note || "", reviewed_at: value?.reviewed_at || "" }; }
  function currentRecord() { return data.records.find((r) => r.candidate_id === state.selected) || null; }
  function currentReview() { return normalizeReview(reviews[state.selected]); }
  function filtered() { return data.records.filter((record) => { const review = normalizeReview(reviews[record.candidate_id]); const haystack = [record.query_label, record.kg_id, record.triage?.summary, record.execution?.error, record.execution?.error_line, ...(record.evidence || []).map((e) => e.snippet)].join("\n").toLowerCase(); if (state.search && !haystack.includes(state.search)) return false; if (state.kg !== "all" && record.kg_id !== state.kg) return false; if (state.category !== "all" && record.triage?.category !== state.category) return false; const decision = review.decision || "unreviewed"; return state.decision === "all" || decision === state.decision; }); }
  function bind() {
    els.searchInput.addEventListener("input", () => { state.search = els.searchInput.value.trim().toLowerCase(); render(); });
    [[els.kgFilter, "kg"], [els.categoryFilter, "category"], [els.decisionFilter, "decision"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.value; render(); }));
    [els.proposedSparqlInput, els.rationaleInput, els.evidenceIdsInput, els.proposalModelInput, els.reviewerNoteInput].forEach((el) => el.addEventListener("input", update));
    [els.editTypeInput, els.proposalOriginInput].forEach((el) => el.addEventListener("change", update));
    decisionButtons.forEach((button) => button.addEventListener("click", () => { update(button.dataset.decision || ""); render(); }));
    els.prevBtn.addEventListener("click", () => move(-1)); els.nextBtn.addEventListener("click", () => move(1));
    els.exportCorrectionsBtn.addEventListener("click", exportReviews);
    els.clearCorrectionStateBtn.addEventListener("click", () => { if (confirm("Clear all local SPARQL correction decisions for this bundle?")) { reviews = {}; saveReviews(); render(); } });
  }
  function update(forcedDecision) { const record = currentRecord(); if (!record) return; const review = { decision: typeof forcedDecision === "string" ? forcedDecision : currentReview().decision, proposed_sparql: els.proposedSparqlInput.value.trim(), edit_type: els.editTypeInput.value, rationale: els.rationaleInput.value.trim(), evidence_ids: els.evidenceIdsInput.value.split(",").map((v) => v.trim()).filter(Boolean), proposal_origin: els.proposalOriginInput.value, proposal_model: els.proposalModelInput.value.trim(), reviewer_note: els.reviewerNoteInput.value.trim(), reviewed_at: new Date().toISOString() }; if (!review.decision && !review.proposed_sparql && !review.rationale && !review.reviewer_note) delete reviews[record.candidate_id]; else reviews[record.candidate_id] = review; saveReviews(); showValidation(record, review); }
  function render() { const rows = filtered(); if (!rows.some((r) => r.candidate_id === state.selected)) state.selected = rows[0]?.candidate_id || null; els.visibleCount.textContent = String(rows.length); els.reviewedCount.textContent = String(Object.values(reviews).filter((r) => r?.decision).length); els.recordList.innerHTML = ""; rows.forEach((record) => { const review = normalizeReview(reviews[record.candidate_id]); const button = document.createElement("button"); button.className = "record-item" + (record.candidate_id === state.selected ? " active" : ""); button.innerHTML = `<span class="record-title">${escapeHtml(record.query_label)}</span><span class="record-subline">${escapeHtml(record.triage?.priority)} · ${escapeHtml(record.triage?.category)}</span><span class="record-subline">${escapeHtml(review.decision || "unreviewed")}</span>`; button.addEventListener("click", () => { state.selected = record.candidate_id; render(); }); els.recordList.appendChild(button); }); renderDetail(currentRecord()); }
  function renderDetail(record) { if (!record) { els.detailView.classList.add("hidden"); els.emptyState.classList.remove("hidden"); return; } els.emptyState.classList.add("hidden"); els.detailView.classList.remove("hidden"); const review = currentReview(); els.detailMeta.textContent = `${record.kg_id} · version ${record.base_sparql_version} · ${record.base_sparql_hash}`; els.detailTitle.textContent = record.query_label; els.priorityBadge.textContent = record.triage?.priority || "-"; els.categoryBadge.textContent = (record.triage?.category || "-").replaceAll("_", " "); els.holdoutWarning.textContent = record.sparql_provenance?.retained_edit_count > 0 ? "This query already has retained SPARQL edit history and is permanently ineligible for holdout inclusion." : "Approving an edit will make this query identity permanently ineligible for holdout inclusion."; els.baseSparql.textContent = record.base_sparql || ""; els.triageSummary.textContent = record.triage?.summary || ""; els.executionDetails.innerHTML = Object.entries(record.execution || {}).map(([k, v]) => `<div><p class="section-label">${escapeHtml(k.replaceAll("_", " "))}</p><p>${escapeHtml(String(v))}</p></div>`).join(""); els.proposedSparqlInput.value = review.proposed_sparql || record.proposed_sparql || record.base_sparql || ""; els.editTypeInput.value = review.edit_type; els.rationaleInput.value = review.rationale; els.evidenceIdsInput.value = review.evidence_ids.join(", "); els.proposalOriginInput.value = review.proposal_origin; els.proposalModelInput.value = review.proposal_model; els.reviewerNoteInput.value = review.reviewer_note; decisionButtons.forEach((b) => { const selected = b.dataset.decision === review.decision; b.classList.toggle("active", selected); if (b.dataset.decision) b.setAttribute("aria-pressed", String(selected)); }); els.evidenceList.innerHTML = ""; const evidence = record.evidence || []; els.evidenceCount.textContent = `${evidence.length} evidence items`; evidence.forEach((item) => { const card = document.createElement("div"); card.className = "evidence-card"; card.innerHTML = `<div class="evidence-meta"><span class="pill">${escapeHtml(item.evidence_id || "")}</span><span class="pill">${escapeHtml(item.type || "unknown")}</span></div><p class="snippet">${escapeHtml(item.snippet || "")}</p>`; els.evidenceList.appendChild(card); }); showValidation(record, review); }
  function validateReview(record, review) { const errors = []; if (!review.decision) return errors; if (["approve_edit", "no_edit"].includes(review.decision) && !review.rationale) errors.push("A rationale is required."); if (review.decision === "approve_edit") { if (!EDIT_TYPES.includes(review.edit_type)) errors.push("Select an edit type."); if (!review.proposed_sparql.trim()) errors.push("Proposed SPARQL is required."); if (review.proposed_sparql.trim() === record.base_sparql.trim()) errors.push("The proposed SPARQL is unchanged."); if (!review.evidence_ids.length) errors.push("At least one aligned evidence ID is required."); } if (!["human", "agent", "source_artifact"].includes(review.proposal_origin)) errors.push("Select a supported proposal origin."); if (review.proposal_origin === "agent" && !review.proposal_model) errors.push("Agent proposals require a model or tool identifier."); const valid = new Set((record.evidence || []).map((e) => e.evidence_id)); const unknown = review.evidence_ids.filter((id) => !valid.has(id)); if (unknown.length) errors.push(`Unknown evidence IDs: ${unknown.join(", ")}`); return errors; }
  function showValidation(record, review) { const errors = validateReview(record, review); els.validationMessage.textContent = errors.length ? errors.join(" ") : review.decision ? "Decision is ready to export." : "Choose a decision when triage is complete."; els.validationMessage.classList.toggle("validation-error", Boolean(errors.length)); }
  function exportPayload() { const output = []; for (const record of data.records) { const review = normalizeReview(reviews[record.candidate_id]); if (!review.decision) continue; const errors = validateReview(record, review); if (errors.length) throw new Error(`${record.query_label}: ${errors.join(" ")}`); output.push({ candidate_id: record.candidate_id, candidate_digest: record.candidate_digest, candidate_reason_code: record.triage?.reason_code, kg_id: record.kg_id, query_id: record.query_id, query_label: record.query_label, base_sparql_version: record.base_sparql_version, base_sparql_hash: record.base_sparql_hash, decision: review.decision, proposed_sparql: review.proposed_sparql, edit_type: review.edit_type || null, rationale: review.rationale, evidence_ids: review.evidence_ids, proposal_origin: review.proposal_origin, proposal_model: review.proposal_model || null, reviewer_note: review.reviewer_note || null, reviewed_at: review.reviewed_at }); } return { schema: EXPORT_SCHEMA, mode: "sparql_correction", dataset_id: data.dataset_id, exported_at: new Date().toISOString(), source_bundle_built_at: data.built_at, holdout_input_policy: data.holdout_input_policy, reviews: output }; }
  function exportReviews() { try { const payload = exportPayload(); if (!payload.reviews.length) throw new Error("No correction decisions to export."); const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `musparql-sparql-correction-review-${data.dataset_id}-${new Date().toISOString().replaceAll(":", "-")}.json`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(link.href), 1000); } catch (error) { alert(error.message); } }
  function move(delta) { const rows = filtered(); const index = rows.findIndex((r) => r.candidate_id === state.selected); if (!rows.length) return; state.selected = rows[(index + delta + rows.length) % rows.length].candidate_id; render(); }
  function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c])); }
})();
